### ISSUE TITLE
Regression in 1.3.4

### ISSUE THREAD

**Issue by jcoyne** [rdf-ext/rdf-ext#89]
https://github.com/rdf-ext/rdf-ext/commit/16948b058731bc15afcc4782d42915dac990ac8c#diff-968a1bab460463d4481ab2caee4080f9752dc942b94492b802e2bfde06a0aebbR2

I'm now getting this error:
```
   Cannot find module '@rdfjs/data-model/lib/BlankNode.js' from 'node_modules/rdf-ext/lib/BlankNode.js'

    Require stack:
      node_modules/rdf-ext/lib/BlankNode.js
      node_modules/rdf-ext/lib/DataFactory.js
      node_modules/rdf-ext/index.js
      src/rdf.js

```

when I do:
```
import rdf from 'rdf-ext'
```

This worked fine in 1.3.2.

**Comment by jcoyne** [comment]
I think the package.json needs to raise the dependency on `@rdfjs/data-model` to be `^1.3.0`

**Comment by bergos** [comment]
@jcoyne thanks for reporting. Fixed in the latest patch version. #90
